server:
  port: ${PORT:80}

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://eyvqcfxf5reja3nv.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/xvjj5xhldlyu1oom?characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
    username: b9770bdkwra6r54x
    password: ogwnmm5ogajyfzw8  # 替换为你的JawsDB MySQL密码

  main:
    banner-mode: off

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.itgroup.domain
  configuration:
    map-underscore-to-camel-case: true
